module.exports = {
    "SuperAdminAlarm1Arr": [
        { "message": "Battery1 Voltage High Cut Alarm", "nomenclature": "Bat1-HiVolt", "detail": "alarm" },
        { "message": "Battery1 Voltage Lower Cut Alarm", "nomenclature": "Bat1-LoVolt", "detail": "alarm" },
        { "message": "Battery1 Over Charge Cut Alarm", "nomenclature": "Bat1-OvrChg", "detail": "alarm" },
        { "message": "Battery1 OverLoad Cut Alarm", "nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
        { "message": "Battery1 Over Charge Temperature Cut Alarm", "nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery1 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery1 Low SOC Cut Alarm", "nomenclature": "Bat1-LoSOC", "detail": "alarm" },
        { "message": "Battery1 Low SOH Cut Alarm", "nomenclature": "Bat1-LoSOH", "detail": "alarm" },
        { "message": "Battery1 Voltage High Cut Warning", "nomenclature": "Bat1-HiVolt", "detail": "warning" },
        { "message": "Battery1 Voltage Lower Cut Warning", "nomenclature": "Bat1-LoVolt", "detail": "warning" },
        { "message": "Battery1 Over Charge Cut Warning", "nomenclature": "Bat1-OvrChg", "detail": "warning" },
        { "message": "Battery1 OverLoad Cut Warning", "nomenclature": "Bat1-OvrLoad", "detail": "warning" },
        { "message": "Battery1 Over Charge Temperature Cut Warning", "nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery1 Over Discharge Temperature Cut Warning", "nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery1 Low SOC Cut Warning", "nomenclature": "Bat1-LoSOC", "detail": "warning" },
        { "message": "Battery1 Low SOH Cut Warning", "nomenclature": "Bat1-LoSOH", "detail": "warning" }
      ],
     "SuperAdminAlarm2Arr":[
        { "message": "Battery2 Voltage High Cut Alarm", "nomenclature": "Bat2-HiVolt", "detail": "alarm" },
        { "message": "Battery2 Voltage Lower Cut Alarm", "nomenclature": "Bat2-LoVolt", "detail": "alarm" },
        { "message": "Battery2 Over Charge Cut Alarm", "nomenclature": "Bat2-OvrChg", "detail": "alarm" },
        { "message": "Battery2 OverLoad Cut Alarm", "nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
        { "message": "Battery2 Over Charge Temperature Cut Alarm", "nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery2 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery2 Low SOC Cut Alarm", "nomenclature": "Bat2-LoSOC", "detail": "alarm" },
        { "message": "Battery2 Low SOH Cut Alarm", "nomenclature": "Bat2-LoSOH", "detail": "alarm" },
        { "message": "Battery2 Voltage High Cut Warning", "nomenclature": "Bat2-HiVolt", "detail": "warning" },
        { "message": "Battery2 Voltage Lower Cut Warning", "nomenclature": "Bat2-LoVolt", "detail": "warning" },
        { "message": "Battery2 Over Charge Cut Warning", "nomenclature": "Bat2-OvrChg", "detail": "warning" },
        { "message": "Battery2 OverLoad Cut Warning", "nomenclature": "Bat2-OvrLoad", "detail": "warning" },
        { "message": "Battery2 Over Charge Temperature Cut Warning", "nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery2 Over Discharge Temperature Cut Warning", "nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery2 Low SOC Cut Warning", "nomenclature": "Bat2-LoSOC", "detail": "warning" },
        { "message": "Battery2 Low SOH Cut Warning", "nomenclature": "Bat2-LoSOH", "detail": "warning" }
      ],
      "SuperAdminAlarm3Arr": [
        { "message": "Battery3 Voltage High Cut Alarm", "nomenclature": "Bat3-HiVolt", "detail": "alarm" },
        { "message": "Battery3 Voltage Lower Cut Alarm", "nomenclature": "Bat3-LoVolt", "detail": "alarm" },
        { "message": "Battery3 Over Charge Cut Alarm", "nomenclature": "Bat3-OvrChg", "detail": "alarm" },
        { "message": "Battery3 OverLoad Cut Alarm", "nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
        { "message": "Battery3 Over Charge Temperature Cut Alarm", "nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Low SOC Cut Alarm", "nomenclature": "Bat3-LoSOC", "detail": "alarm" },
        { "message": "Battery3 Low SOH Cut Alarm", "nomenclature": "Bat3-LoSOH", "detail": "alarm" },
        { "message": "Battery3 Voltage High Cut Warning", "nomenclature": "Bat3-HiVolt", "detail": "warning" },
        { "message": "Battery3 Voltage Lower Cut Warning", "nomenclature": "Bat3-LoVolt", "detail": "warning" },
        { "message": "Battery3 Over Charge Cut Warning", "nomenclature": "Bat3-OvrChg", "detail": "warning" },
        { "message": "Battery3 OverLoad Cut Warning", "nomenclature": "Bat3-OvrLoad", "detail": "warning" },
        { "message": "Battery3 Over Charge Temperature Cut Warning", "nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Over Discharge Temperature Cut Warning", "nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Low SOC Cut Warning", "nomenclature": "Bat3-LoSOC", "detail": "warning" },
        { "message": "Battery3 Low SOH Cut Warning", "nomenclature": "Bat3-LoSOH", "detail": "warning" }
      ],
      "SuperAdminAlarm4Arr": [
        { "message": "Battery1 Voltage High Cut Alarm", "Nomenclature": "Bat1-HiVolt" },
        { "message": "Battery1 Voltage Lower Cut Alarm", "Nomenclature": "Bat1-LoVolt" },
        { "message": "Battery1 Over Charge Cut Alarm", "Nomenclature": "Bat1-OvrChg" },
        { "message": "Battery1 OverLoad Cut Alarm", "Nomenclature": "Bat1-OvrLoad" },
        { "message": "Battery1 Over Charge Temperature Cut Alarm", "Nomenclature": "Bat1-ChgOvrTemp" },
        { "message": "Battery1 Over Discharge Temperature Cut Alarm", "Nomenclature": "Bat1-DischgOvrTemp" },
        { "message": "Battery1 Low SOC Cut Alarm", "Nomenclature": "Bat1-LoSOC" },
        { "message": "Battery1 Low SOH Cut Alarm", "Nomenclature": "Bat1-LoSOH" },
        { "message": "Battery1 Voltage High Cut Warning", "Nomenclature": "Bat1-HiVolt" },
        { "message": "Battery1 Voltage Lower Cut Warning", "Nomenclature": "Bat1-LoVolt" },
        { "message": "Battery1 Over Charge Cut Warning", "Nomenclature": "Bat1-OvrChg" },
        { "message": "Battery1 OverLoad Cut Warning", "Nomenclature": "Bat1-OvrLoad" },
        { "message": "Battery1 Over Charge Temperature Cut Warning", "Nomenclature": "Bat1-ChgOvrTemp" },
        { "message": "Battery1 Over Discharge Temperature Cut Warning", "Nomenclature": "Bat1-DischgOvrTemp" },
        { "message": "Battery1 Low SOC Cut Warning", "Nomenclature": "Bat1-LoSOC" },
        { "message": "Battery1 Low SOH Cut Warning", "Nomenclature": "Bat1-LoSOH" }
      ],
    
    "FleetManagerAlarm1Arr":[
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat1-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
      "FleetManagerAlarm2Arr": [
        { "message": "Reinitialise Charging", "Nomenclature": "Bat2-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat2-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat2-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
     "FleetManagerAlarm3Arr": [
        { "message": "Reinitialise Charging", "Nomenclature": "Bat3-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat3-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat3-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
      "FleetManagerAlarm4Arr": [
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-HiVolt" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-OvrChg" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-ChgOvrTemp" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-DischgOvrTemp" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC" },
        { "message": "Change Battery", "Nomenclature": "Bat1-LoSOH" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-HiVolt" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-OvrChg" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-ChgOvrTemp" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat1-DischgOvrTemp" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC" },
        { "message": "", "Nomenclature": "" }
      ],
    
      "SystemIntegraterAlarm1Arr": [
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat1-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat1-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat1-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat1-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
      "SystemIntegraterAlarm2Arr":[
        { "message": "Reinitialise Charging", "Nomenclature": "Bat2-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat2-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat2-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat2-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat2-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
      "SystemIntegraterAlarm3Arr": [
        { "message": "Reinitialise Charging", "Nomenclature": "Bat3-HiVolt", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "alarm" },
        { "message": "Reinitialise Charging", "Nomenclature": "Bat3-OvrChg", "detail": "alarm" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
        { "message": "Wait for Normal Temp", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "alarm" },
        { "message": "Change Battery", "Nomenclature": "Bat3-LoSOH", "detail": "alarm" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-HiVolt", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoVolt", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-OvrChg", "detail": "warning" },
        { "message": "Stop Vehicle", "Nomenclature": "Bat3-OvrLoad", "detail": "warning" },
        { "message": "Stop Charging", "Nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
        { "message": "Stop Vehicle ", "Nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
        { "message": "Start Charging", "Nomenclature": "Bat3-LoSOC", "detail": "warning" },
        { "message": "", "Nomenclature": "", "detail": "warning" }
      ],
      "SystemIntegraterAlarm4Arr": [],
    
      "BatteryManufacturerAlarm1Arr":[
        { "message": "Battery1 Voltage High Cut Alarm", "nomenclature": "Bat1-HiVolt", "detail": "alarm" },
        { "message": "Battery1 Voltage Lower Cut Alarm", "nomenclature": "Bat1-LoVolt", "detail": "alarm" },
        { "message": "Battery1 Over Charge Cut Alarm", "nomenclature": "Bat1-OvrChg", "detail": "alarm" },
        { "message": "Battery1 OverLoad Cut Alarm", "nomenclature": "Bat1-OvrLoad", "detail": "alarm" },
        { "message": "Battery1 Over Charge Temperature Cut Alarm", "nomenclature": "Bat1-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery1 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat1-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery1 Low SOC Cut Alarm", "nomenclature": "Bat1-LoSOC", "detail": "alarm" },
        { "message": "Battery1 Low SOH Cut Alarm", "nomenclature": "Bat1-LoSOH", "detail": "alarm" },
        { "message": "Battery1 Voltage High Cut Warning", "nomenclature": "Bat1-HiVolt", "detail": "warning" },
        { "message": "Battery1 Voltage Lower Cut Warning", "nomenclature": "Bat1-LoVolt", "detail": "warning" },
        { "message": "Battery1 Over Charge Cut Warning", "nomenclature": "Bat1-OvrChg", "detail": "warning" },
        { "message": "Battery1 OverLoad Cut Warning", "nomenclature": "Bat1-OvrLoad", "detail": "warning" },
        { "message": "Battery1 Over Charge Temperature Cut Warning", "nomenclature": "Bat1-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery1 Over Discharge Temperature Cut Warning", "nomenclature": "Bat1-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery1 Low SOC Cut Warning", "nomenclature": "Bat1-LoSOC", "detail": "warning" },
        { "message": "Battery1 Low SOH Cut Warning", "nomenclature": "Bat1-LoSOH", "detail": "warning" }
      ],
      "BatteryManufacturerAlarm2Arr": [
        { "message": "Battery2 Voltage High Cut Alarm", "nomenclature": "Bat2-HiVolt", "detail": "alarm" },
        { "message": "Battery2 Voltage Lower Cut Alarm", "nomenclature": "Bat2-LoVolt", "detail": "alarm" },
        { "message": "Battery2 Over Charge Cut Alarm", "nomenclature": "Bat2-OvrChg", "detail": "alarm" },
        { "message": "Battery2 OverLoad Cut Alarm", "nomenclature": "Bat2-OvrLoad", "detail": "alarm" },
        { "message": "Battery2 Over Charge Temperature Cut Alarm", "nomenclature": "Bat2-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery2 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat2-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery2 Low SOC Cut Alarm", "nomenclature": "Bat2-LoSOC", "detail": "alarm" },
        { "message": "Battery2 Low SOH Cut Alarm", "nomenclature": "Bat2-LoSOH", "detail": "alarm" },
        { "message": "Battery2 Voltage High Cut Warning", "nomenclature": "Bat2-HiVolt", "detail": "warning" },
        { "message": "Battery2 Voltage Lower Cut Warning", "nomenclature": "Bat2-LoVolt", "detail": "warning" },
        { "message": "Battery2 Over Charge Cut Warning", "nomenclature": "Bat2-OvrChg", "detail": "warning" },
        { "message": "Battery2 OverLoad Cut Warning", "nomenclature": "Bat2-OvrLoad", "detail": "warning" },
        { "message": "Battery2 Over Charge Temperature Cut Warning", "nomenclature": "Bat2-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery2 Over Discharge Temperature Cut Warning", "nomenclature": "Bat2-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery2 Low SOC Cut Warning", "nomenclature": "Bat2-LoSOC", "detail": "warning" },
        { "message": "Battery2 Low SOH Cut Warning", "nomenclature": "Bat2-LoSOH", "detail": "warning" }
      ],
      "BatteryManufacturerAlarm3Arr": [
        { "message": "Battery3 Voltage High Cut Alarm", "nomenclature": "Bat3-HiVolt", "detail": "alarm" },
        { "message": "Battery3 Voltage Lower Cut Alarm", "nomenclature": "Bat3-LoVolt", "detail": "alarm" },
        { "message": "Battery3 Over Charge Cut Alarm", "nomenclature": "Bat3-OvrChg", "detail": "alarm" },
        { "message": "Battery3 OverLoad Cut Alarm", "nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
        { "message": "Battery3 Over Charge Temperature Cut Alarm", "nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Low SOC Cut Alarm", "nomenclature": "Bat3-LoSOC", "detail": "alarm" },
        { "message": "Battery3 Low SOH Cut Alarm", "nomenclature": "Bat3-LoSOH", "detail": "alarm" },
        { "message": "Battery3 Voltage High Cut Warning", "nomenclature": "Bat3-HiVolt", "detail": "warning" },
        { "message": "Battery3 Voltage Lower Cut Warning", "nomenclature": "Bat3-LoVolt", "detail": "warning" },
        { "message": "Battery3 Over Charge Cut Warning", "nomenclature": "Bat3-OvrChg", "detail": "warning" },
        { "message": "Battery3 OverLoad Cut Warning", "nomenclature": "Bat3-OvrLoad", "detail": "warning" },
        { "message": "Battery3 Over Charge Temperature Cut Warning", "nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Over Discharge Temperature Cut Warning", "nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Low SOC Cut Warning", "nomenclature": "Bat3-LoSOC", "detail": "warning" },
        { "message": "Battery3 Low SOH Cut Warning", "nomenclature": "Bat3-LoSOH", "detail": "warning" }
      ],
      "BatteryManufacturerAlarm4Arr" : [
        { "message": "Bat1-LoCycleCnt", "nomenclature": "Bat3-HiVolt", "detail": "" },
        { "message": "Battery3 Voltage Lower Cut Alarm", "nomenclature": "Bat3-LoVolt", "detail": "alarm" },
        { "message": "Battery3 Over Charge Cut Alarm", "nomenclature": "Bat3-OvrChg", "detail": "alarm" },
        { "message": "Battery3 OverLoad Cut Alarm", "nomenclature": "Bat3-OvrLoad", "detail": "alarm" },
        { "message": "Battery3 Over Charge Temperature Cut Alarm", "nomenclature": "Bat3-ChgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Over Discharge Temperature Cut Alarm", "nomenclature": "Bat3-DischgOvrTemp", "detail": "alarm" },
        { "message": "Battery3 Low SOC Cut Alarm", "nomenclature": "Bat3-LoSOC", "detail": "alarm" },
        { "message": "Battery3 Low SOH Cut Alarm", "nomenclature": "Bat3-LoSOH", "detail": "alarm" },
        { "message": "Battery3 Voltage High Cut Warning", "nomenclature": "Bat3-HiVolt", "detail": "warning" },
        { "message": "Battery3 Voltage Lower Cut Warning", "nomenclature": "Bat3-LoVolt", "detail": "warning" },
        { "message": "Battery3 Over Charge Cut Warning", "nomenclature": "Bat3-OvrChg", "detail": "warning" },
        { "message": "Battery3 OverLoad Cut Warning", "nomenclature": "Bat3-OvrLoad", "detail": "warning" },
        { "message": "Battery3 Over Charge Temperature Cut Warning", "nomenclature": "Bat3-ChgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Over Discharge Temperature Cut Warning", "nomenclature": "Bat3-DischgOvrTemp", "detail": "warning" },
        { "message": "Battery3 Low SOC Cut Warning", "nomenclature": "Bat3-LoSOC", "detail": "warning" },
        { "message": "Battery3 Low SOH Cut Warning", "nomenclature": "Bat3-LoSOH", "detail": "warning" }
      ]	
    }